// <auto-generated />
using System;
using AuthServer.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace AuthServer.Migrations
{
    [DbContext(typeof(AuthDbContext))]
    partial class AuthDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("AuthServer.Entities.AppRole", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("IsActive")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(true);

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.HasKey("Id");

                    b.HasIndex("Name")
                        .IsUnique();

                    b.ToTable("Roles");

                    b.HasData(
                        new
                        {
                            Id = new Guid("22222222-2222-2222-2222-222222222221"),
                            Description = "Full system access. Manage users, roles, catalog, orders and plafroem setting.",
                            IsActive = true,
                            Name = "Admin"
                        },
                        new
                        {
                            Id = new Guid("22222222-2222-2222-2222-222222222222"),
                            Description = "End user who browses products, places orders, makes payments, and manages their profile.",
                            IsActive = true,
                            Name = "Customer"
                        },
                        new
                        {
                            Id = new Guid("22222222-2222-2222-2222-222222222223"),
                            Description = "Merchant who lists products, manages inventory/pricing, and fulfills customer order.",
                            IsActive = true,
                            Name = "Seller"
                        },
                        new
                        {
                            Id = new Guid("22222222-2222-2222-2222-222222222224"),
                            Description = "Delivery agaent responsible for pickup, shipment tracking, and last-mile delivery updates.",
                            IsActive = true,
                            Name = "DeliveryPartner"
                        });
                });

            modelBuilder.Entity("AuthServer.Entities.AppUser", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("CreatedUtc")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("GETUTCDATE()");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasMaxLength(300)
                        .HasColumnType("nvarchar(300)");

                    b.Property<string>("PhoneNumber")
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.HasKey("Id");

                    b.HasIndex("Email")
                        .IsUnique();

                    b.ToTable("Users");

                    b.HasData(
                        new
                        {
                            Id = new Guid("aaaaaaaa-aaaa-aaaa-aaaa-aaaaaaaaaaaa"),
                            CreatedUtc = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Email = "admin@ecommerce.com",
                            FirstName = "System",
                            IsActive = true,
                            LastName = "Admin",
                            PasswordHash = "$2a$11$lSA2QnkivSQC8R9F1ZeZOes6fh4XwX8W8nZ4Zm/AVikODCY5MzDr2",
                            PhoneNumber = "999999999"
                        },
                        new
                        {
                            Id = new Guid("22222222-bbbb-bbbb-bbbb-222222222222"),
                            CreatedUtc = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Email = "customer@ecommerce.com",
                            FirstName = "Demo",
                            IsActive = true,
                            LastName = "Customer",
                            PasswordHash = "$2a$11$Aq8dWGslPMFYybvv6JgO2OOTfgVBxagIaj/JuhDGf/GtYOltqYvg6",
                            PhoneNumber = "8888888888"
                        },
                        new
                        {
                            Id = new Guid("33333333-cccc-cccc-cccc-333333333333"),
                            CreatedUtc = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Email = "seller@ecommerce.com",
                            FirstName = "Demo",
                            IsActive = true,
                            LastName = "Seller",
                            PasswordHash = "$2a$11$x6a3VMzdFImQ3ZKE01dkHesNvVTwWVl75nzrMtssceKhnjnxt2MFa",
                            PhoneNumber = "7777777777"
                        },
                        new
                        {
                            Id = new Guid("44444444-dddd-dddd-dddd-444444444444"),
                            CreatedUtc = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Email = "delivery@ecommerce.com",
                            FirstName = "Demo",
                            IsActive = true,
                            LastName = "Rider",
                            PasswordHash = "$2a$11$8jXB5nLn3qNuV.WKs5480.779PKRHqgg6S7fw8A.oCLy6.EyhZGx2",
                            PhoneNumber = "6666666666"
                        });
                });

            modelBuilder.Entity("AuthServer.Entities.AppUserRole", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid?>("AssignedByUserId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("AssignedUtc")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("GETUTCDATE()");

                    b.Property<string>("Notes")
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid>("RoleId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("AssignedByUserId");

                    b.HasIndex("RoleId");

                    b.HasIndex("UserId", "RoleId")
                        .IsUnique();

                    b.ToTable("UserRoles");

                    b.HasData(
                        new
                        {
                            Id = new Guid("10000000-0000-0000-0000-000000000001"),
                            AssignedByUserId = new Guid("aaaaaaaa-aaaa-aaaa-aaaa-aaaaaaaaaaaa"),
                            AssignedUtc = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Notes = "Seeded admin",
                            RoleId = new Guid("22222222-2222-2222-2222-222222222221"),
                            UserId = new Guid("aaaaaaaa-aaaa-aaaa-aaaa-aaaaaaaaaaaa")
                        },
                        new
                        {
                            Id = new Guid("10000000-0000-0000-0000-000000000002"),
                            AssignedByUserId = new Guid("22222222-bbbb-bbbb-bbbb-222222222222"),
                            AssignedUtc = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Notes = "Seeded customer",
                            RoleId = new Guid("22222222-2222-2222-2222-222222222222"),
                            UserId = new Guid("22222222-bbbb-bbbb-bbbb-222222222222")
                        },
                        new
                        {
                            Id = new Guid("10000000-0000-0000-0000-000000000003"),
                            AssignedByUserId = new Guid("33333333-cccc-cccc-cccc-333333333333"),
                            AssignedUtc = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Notes = "Seeded seller",
                            RoleId = new Guid("22222222-2222-2222-2222-222222222223"),
                            UserId = new Guid("33333333-cccc-cccc-cccc-333333333333")
                        },
                        new
                        {
                            Id = new Guid("10000000-0000-0000-0000-000000000004"),
                            AssignedByUserId = new Guid("aaaaaaaa-aaaa-aaaa-aaaa-aaaaaaaaaaaa"),
                            AssignedUtc = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Notes = "Seeded admin",
                            RoleId = new Guid("22222222-2222-2222-2222-222222222224"),
                            UserId = new Guid("44444444-dddd-dddd-dddd-444444444444")
                        });
                });

            modelBuilder.Entity("AuthServer.Entities.ClientApp", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("ClientId")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("ClientSecretHash")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<DateTime>("CreatedUtc")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("GETUTCDATE()");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.HasKey("Id");

                    b.HasIndex("ClientId")
                        .IsUnique();

                    b.ToTable("ClientApps");

                    b.HasData(
                        new
                        {
                            Id = new Guid("11111111-1111-1111-1111-111111111111"),
                            ClientId = "QaFKlLnRkjht0cnkmVYbw",
                            ClientSecretHash = "$2a$11$ua9Mhe.rPlAGvh7jH5bRguRVuIo8Ewqfofmss17u9jxbZPP34wFXW",
                            CreatedUtc = new DateTime(2026, 3, 1, 17, 37, 16, 55, DateTimeKind.Utc).AddTicks(5217),
                            IsActive = true,
                            Name = "E-Commerce Web Client"
                        },
                        new
                        {
                            Id = new Guid("11111111-1111-1111-1111-111111111112"),
                            ClientId = "u5JH6gdhmAB6VBqBprfDHQ",
                            ClientSecretHash = "$2a$11$581VAtEU5CrS/Xt0BDFQ6OkEXAFzDxDoSlme3sY08U85r.OB.Wgjy",
                            CreatedUtc = new DateTime(2026, 3, 1, 17, 37, 16, 222, DateTimeKind.Utc).AddTicks(6255),
                            IsActive = true,
                            Name = "E-Commerce Android Client"
                        },
                        new
                        {
                            Id = new Guid("11111111-1111-1111-1111-111111111113"),
                            ClientId = "8dj5ti3zXBUjpgQ_mH-bGA",
                            ClientSecretHash = "$2a$11$1TdaxnUqnYsgIasdZqS5/eTzjY50X2gbftjY9Sm7yODiyeUXEA9ZO",
                            CreatedUtc = new DateTime(2026, 3, 1, 17, 37, 16, 388, DateTimeKind.Utc).AddTicks(9125),
                            IsActive = true,
                            Name = "E-Commerce iOS Client"
                        });
                });

            modelBuilder.Entity("AuthServer.Entities.RefreshToken", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("CreatedUtc")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("GETUTCDATE()");

                    b.Property<DateTime>("ExpiresUtc")
                        .HasColumnType("datetime2");

                    b.Property<Guid?>("ParentTokenId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid?>("ReplaceByTokenId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("RevokedReason")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("RevokedUtc")
                        .HasColumnType("datetime2");

                    b.Property<Guid>("SessionId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("TokenHash")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.HasKey("Id");

                    b.HasIndex("ParentTokenId");

                    b.HasIndex("ReplaceByTokenId");

                    b.HasIndex("SessionId");

                    b.HasIndex("TokenHash")
                        .IsUnique();

                    b.ToTable("RefreshTokens");
                });

            modelBuilder.Entity("AuthServer.Entities.UserSession", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("ClientAppId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("CreatedUtc")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("GETUTCDATE()");

                    b.Property<string>("DeviceId")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("IpAddress")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<DateTime>("LastSeenUtc")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("GETUTCDATE()");

                    b.Property<string>("LoginLocation")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<DateTime?>("RevokedUtc")
                        .HasColumnType("datetime2");

                    b.Property<string>("UserAgent")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("ClientAppId");

                    b.HasIndex("UserId", "ClientAppId", "DeviceId");

                    b.ToTable("UserSessions");
                });

            modelBuilder.Entity("AuthServer.Entities.AppUserRole", b =>
                {
                    b.HasOne("AuthServer.Entities.AppUser", null)
                        .WithMany()
                        .HasForeignKey("AssignedByUserId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("AuthServer.Entities.AppRole", "Role")
                        .WithMany("UserRoles")
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("AuthServer.Entities.AppUser", "User")
                        .WithMany("UserRoles")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Role");

                    b.Navigation("User");
                });

            modelBuilder.Entity("AuthServer.Entities.RefreshToken", b =>
                {
                    b.HasOne("AuthServer.Entities.RefreshToken", "ParentToken")
                        .WithMany()
                        .HasForeignKey("ParentTokenId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("AuthServer.Entities.RefreshToken", "ReplacedByToken")
                        .WithMany()
                        .HasForeignKey("ReplaceByTokenId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("AuthServer.Entities.UserSession", "Session")
                        .WithMany("RefreshTokens")
                        .HasForeignKey("SessionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("ParentToken");

                    b.Navigation("ReplacedByToken");

                    b.Navigation("Session");
                });

            modelBuilder.Entity("AuthServer.Entities.UserSession", b =>
                {
                    b.HasOne("AuthServer.Entities.ClientApp", "ClientApp")
                        .WithMany()
                        .HasForeignKey("ClientAppId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("AuthServer.Entities.AppUser", "User")
                        .WithMany("Sessions")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("ClientApp");

                    b.Navigation("User");
                });

            modelBuilder.Entity("AuthServer.Entities.AppRole", b =>
                {
                    b.Navigation("UserRoles");
                });

            modelBuilder.Entity("AuthServer.Entities.AppUser", b =>
                {
                    b.Navigation("Sessions");

                    b.Navigation("UserRoles");
                });

            modelBuilder.Entity("AuthServer.Entities.UserSession", b =>
                {
                    b.Navigation("RefreshTokens");
                });
#pragma warning restore 612, 618
        }
    }
}
